version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  django_app:
    build:
      context: .
    image: hsris/my-notes-app:latest
    container_name: "django_cont"
    ports:
      - "8002:8000"  # Changed host port to 8002
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    env_file:
      - ".env"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

  kong:
    image: kong/kong-gateway:3.8.0.0
    container_name: "kong"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/app/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8003  # Updated Admin API port to 8003
      - KONG_PROXY_LISTEN=0.0.0.0:8000
    ports:
      - "8000:8000"  # Kong Proxy port
      - "8003:8003"  # Updated Kong Admin API port
    volumes:
      - ./kong/kong.yml:/app/kong.yml:ro
    networks:
      - notes-app-nw
    depends_on:
      - django_app

networks:
  notes-app-nw:
